name: console_bit
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  dio: ^4.0.6
  get_storage: ^2.0.3
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  telephony: ^0.1.4
  shimmer: ^2.0.0
  url_launcher: ^6.1.3
  dropdown_search: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
  